services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
 
    container_name: rg-frontend
    restart: always
    extra_hosts:
      - "admin.radhagovindadasa.com:172.18.0.2"
    networks:
      - traefik_net
networks:
  traefik_net:
    name: "traefik_net"  # или какое имя у вас реально в Docker
    external: true

