import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/providers/StoreProvider";
import Player from "@/components/player/Player";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["600"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <StoreProvider>
          {children}
          <Player></Player>
        </StoreProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
