import type { Metadata } from "next";
// import { Mulish } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/styled-components/StyledComponentsRegistry";
import { ThemeProvider } from "styled-components";
import { theme } from "@/lib/styled-components/theme";
import Providers from "@/components/Providers";
import StoreProvider from "@/components/providers/StoreProvider";
import Player from "@/components/player/Player";

// const mulish = Mulish({
//   subsets: ["latin", "cyrillic"],
//   weight: ["400", "500", "600", "700", "800"],
//   variable: "--font-mulish",
// });




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
       <StoreProvider>
       {children}
       </StoreProvider>
     
       <div id="modal-root"></div>
      </body>
    </html>
  );
}
